### ISSUE TITLE
How to use this new wallet and some issues?

### ISSUE THREAD

**Issue by zydjohnHotmail** [heddhshan/W-Wallet#1]
Hello:
I found your repo for this new wallet, it is rather interesting. I want to know something about this repo:
First, can I create online/offline wallet to hold tokens from different networks and receive, send to other address via different networks?
For example, if I want to create one wallet address, which can receive USDT from ERC20 chain, then after paying the gas fees, send the received USDT tokens to another address via BEP20.  I think ERC20 and BEP20 are EVM chains, so this should be not difficult, but I want to know if I can do this via the repo.
Another thing I want to know is how many different networks this wallet can support?
I want to be able to support at least the following networks: ERC20, BEP20, TRC20, Solana or even HECO (Huobi).
Let me know if your wallet API can do all the above or some of them.

Also, how many tokens your wallet can support, like: USDT, BTC, ETH and many many more?
By the way, does your wallet support sending tokens via their contract address, for example, for USDT, its contract address is: 0xdac17f958d2ee523a2206206994597c13d831ec7
Do you have a list for different tokens with their contract address, like: BTC, ETH, HT and others?

Finally, I have downloaded the source code in ZIP file, and unzipped it and try to run it using Visual Studio 2022 on my Windows 10 PC, but I got the following errors for 2 projects in the solution.

Setup_OfflineWallet\Setup_OfflineWallet.vdproj: The application which this project type is based on was not found. Please try this link for further information: 54435603-dbb4-11d2-8724-00a0c9a8b90c
Setup_OnlineWallet
Message
Setup_OnlineWallet\Setup_OnlineWallet.vdproj: The application which this project type is based on was not found. Please try this link for further information: 54435603-dbb4-11d2-8724-00a0c9a8b90c

It seems you are using some SDK which VS 2022 didn’t know, my VS2022 version is: 17.4.2
What is .vdproj project?
Besides, do you plan to publish some NUGET package, so it will be easy to use.
I want to be able to use it for C# project target .NET 7.0 or at least .NET 6.0; as .NET 5.0 is already out of support, for legacy platform, simply forget them.
Please advise,
Thanks,

**Comment by heddhshan** [comment]
It is recommended that you run the exe program first, which supports testing the network

**Comment by zydjohnHotmail** [comment]
Hello:
I run the exe, the following is the output:
F:\Download\W-Wallet-master\Nethereum.Uniswap-V2-and-V3-main\testchain\gethclique>geth.exe
INFO [12-08|09:37:42.290] Starting Geth on Ethereum mainnet...
INFO [12-08|09:37:42.293] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [12-08|09:37:42.298] Maximum peer count                       ETH=50 LES=0 total=50
INFO [12-08|09:37:42.402] Set global gas cap                       cap=25000000
....
It seems working.  But I want to know if I can use this for main net, not only for test net.
By the way, I want to know is how many different networks this wallet can support?
I want to be able to support at least the following networks: ERC20, BEP20, Solana or even HECO (Huobi).
I want to do cross chain receive and send tokens.
For example, using the same address, I want to be able to receive USDT, ETH and other tokens via BEP20 or even HECO chain (Huobi), then after paying gas fees, send USDT or ETH to other address via ERC20 chain or via Solana network?
If yes, please show me some code on how to do this.
Finally, how can I get rid error message when using Visual Studio 2022 to load the solution?
Thanks,

**Comment by zydjohnHotmail** [comment]
Hello:

I want to compile the soultion in Visual Studio 2022, but I got one error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IEtherTransferService' does not contain a definition for 'CalculateTotalAmountToTransferWholeBalanceInEther' and no accessible extension method 'CalculateTotalAmountToTransferWholeBalanceInEther' accepting a first argument of type 'IEtherTransferService' could be found (are you missing a using directive or an assembly reference?)	Nethereum.Uniswap.Testing (net5.0)	F:\Download\W-Wallet-master\Nethereum.Uniswap-V2-and-V3-main\Nethereum.Uniswap.Testing\TransferEtherTests.cs	99	Active

It is in file: TransferEtherTests.cs:
(W-Wallet-master\Nethereum.Uniswap-V2-and-V3-main\Nethereum.Uniswap.Testing\TransferEtherTests.cs)
For lines: 98 to 99, for this statement:

var totalAmountBack =
await transferService.CalculateTotalAmountToTransferWholeBalanceInEther(toAddress, 2);

This seems to be an important statement,
Let me know how to fix this.

**Comment by rahuliyer95** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
zhuanghamiao, @surendersinghIT, @GGAlanSmithee, @Quanxuke, @davisuga, @vbortone, @joaoantoniomartinsfilho, @big-kahuna-burger, @sunguoxing0628, @OlegJakushkin, @lynnroyal, @leglutz, @ohhkaneda, @dvs39, @Daunt02, @juanfranblanco, @ulopong, @0xF6, @gaoxiangxyz, @DheerajP
